name: Close Actions

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-close-actions.yml@5a0a828ec10bcebf7c980d13fca16f99be69f6d0 # v2.4.0
    permissions:
      issues: write
      pull-requests: write
      actions: write

  cleanup:
    name: Cleanup from previous test runs
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Delete previous test release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release delete vtest-${{ github.ref_name }} --cleanup-tag -y || echo "No previous release to delete"
