name: Enforce conventions

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-conventions.yml@v2.0.0
    permissions:
      issues: write
      pull-requests: write
